### ISSUE TITLE
Can't able to send or recive message

### ISSUE THREAD

**Issue by yanicodeverse** [yanicodeverse/chat-nexus#14]
Uncaught TypeError: Cannot read properties of null (reading 'emit')
    at sendMessage (main-8c0de078.js:34:87517)
    at onSubmit (main-8c0de078.js:34:88514)
    at Object.jt (main-8c0de078.js:29:16652)
    at Ft (main-8c0de078.js:29:16806)
    at main-8c0de078.js:29:36745
    at zo (main-8c0de078.js:29:36840)
    at Do (main-8c0de078.js:29:37254)
    at main-8c0de078.js:29:42693
    at sc (main-8c0de078.js:29:106159)
    at Ot (main-8c0de078.js:29:15783)

**Comment by rakshyak-98** [comment]
resolved: 6fe3f9da39464da876ede4088ceb8785dc295fd0
